sudo: false
language: php

php:
  - 5.6

before_script:
  - mysql -e 'create database bible character set utf8 collate utf8_unicode_ci;'
  - npm install
  - php composer.phar selfupdate
  - php composer.phar install
  - gulp default

script:
# first test will run the migrations
  - phpunit --configuration phpunit.xml

after_success:
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host szentiras.hu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git remote add deploy szentiras_hu_git@szentiras.hu:/home/szentiras_hu_git/github/borazslo/szentiras.hu.git
  - git push deploy $TRAVIS_BRANCH

after_failure: "cat /home/travis/build/borazslo/szentiras.hu/storage/logs/laravel.log"

cache:
  directories:
    - vendor
    - node_modules
    - bower_components

env:
  global:
  - DB_USERNAME=root
  - DB_PASSWORD=""
  - APP_KEY=NbtLDkclj9j3pmj4hOONo8vhgXmSASdD
  - secure: EMWhgRZT6WGhjmFlhw63hivKAr1zq3MfW4TNErwer8XAllXTWuV+T1KSb+1aNsH4JG34Y4KOn20mGBLEG29WiZ0k8dx99afnlJtw5xY76vHfTT+RvST9MFLo17mlthdIu40MIxnyMKUVgS4y0kohAUT7uFD+LTWjx0G0V8QVF4w=
  - secure: KRNcmD/E4B0D6Tco2v3vKEpAFfeuBRtth7sEc3qZKyzp/lPqRpfVuJBOdtkP05Wd6XbjhSaAVQ08RwhRSGtAMlq7JQGjm+RJxB5bXtyRJQtgSeBYJNVa+qhUpAJ22BLo3pBZU7m+Zp3u0qBXi5euGgqyyPes7gjTPk6Wvg0Erx8=
  - secure: KUaxJ0Ke+LMxkoS92Axx14Z4TmlT7DvKqKZFXF/vbt8hwMptlPEeEqJ5/r+n8yYYuP60fSBXzM7ZW7EV/n2Rvu9HxbIGuvssLvFEE+ePwkXJViOikA4crh9UsTb1C/40TNShEPaY1ZWvAO6qwxj1kdrCJ4rHpPNC32pUj59jHRo=
  - secure: mD77HAz5HCFrsjeH/FY0FyxNITpf7BtA1UYcdkS5lmqZmzLLTatoCQq5Kp7ojhAfpqQCCLGpGP4wmkpLIELjSIC2IMUH8bf2IXpr0vBSYupMxhP6aCVG0HyAkPH/IJZWw0NIibvZP+gZSJmszIAAmHdCmF+bKHPKWaumpYjKh3U=
  - secure: fffPsV+FQRK4E1wfTQR/CIFrY4Tl9WSMJ/ESdObH4ht7/cNia3a2UDVgw6uJeYHdwK2YumT0Om1Y8tKLf5/6qU9vtqp6JgmIJsxHQ+c3v7XfoCXsx4lUatn4fvzzZZXiplGqwpSIt4867P0tGnMos6M4Fa6VL9nAYLrnTrUSd98=
  - secure: rE27pmsNwdAwCLHrZX0Xax7U7mHpW/oWiUTLFSe3FQCx1+Ye5JZYo6LAZoYExwOqfcpvD8vRYnOycPH1EbP7vpNCfZIAoD9s9Hzj1gjqok2U0mvRpUWaCfeV9tEY8vhZrbp/80BCrPCqnpAzpo8SkIMMB1jdy+7vs6P11yazcfA=
  - secure: sAIUdW0aGIEixm2ZhFF7cXZcJfFQROa+UwBE5jmibbg2J9qHeso7h/7pK7K4sr65iCLi5vZ0mZ3B7TacVWVlcEWFWJIRim7XD9nYSV8DjzJ95r7I0EQx1SGunBkXS55NaS5jTlctYVz9HuDUsf5YhXgjtnI0E0hCJFayHxHrAeg=
  - secure: pJFlDAyULPyiroA58Zcc/KGIU13Q8Ehma8WrWw3FhwKysOS/aenJUUSBkV83ue4eboRjbdkEggJnOKpjTzO0zvd/W6BJmwtIcpHhD0npczt+03NO9lDolebVnIfMgcpXc+p0KLGjZTs31KIuAZFTPY5jYnRDveUIb6xIY6c7YxA=
  - secure: fUOCP8PZrvahT7XQBzVXqdDHJvKKGJwXcuE5ynuFmRXyC6HP5wX9zfGRlnxlA6QQEQeh9cdQaNmJvzXRVXpVUAB+XXCCmEbLj6FhA0xt5qrl1PblBvW43upPtENhw0RVTJ09gvLFWqA3Zf1L8AD0Lf0aaHEOVPk6dMNjDz+AWdk=
  - secure: IGi5tUFKbsW4TonStjtASZzmfr0Y676RAZErDi43V8GEzNQ8/FIeWsacjIQ+CjE6daWzwoUUGauzk3PeGwg5st87bcUbup9d8tDu8jHIYrNInTrJIg7Nd/K1AUvKrndyMGahOUVWovEURVk9TpjrtXND5He4/T+Odz6ruLueUso=
  - secure: A0IWBUbP6EZqiVJr2yyJh5t0ZEgBvjoF21zFgF+DeOEXfQiKAmjDJfjICbgTRYEaIHQaSd3EKlrM+7vZzbMxt80HogLP1OaE/8oqeNipLSRFWcEmvojdxRKFPOaC1zYJlNtPmXhXyEV0v7f8eJQ2MHTcDyqbj0MT3+XeXTHEbtQ=
  - secure: leVowoNhKSraulw6hVJhk9gYZ00DsCi3E3fzIpWPzif+CLGkFoR0j3D1Gq0UnKg7HmHWAA0uo2LrND0YREOvopE4+U/AAuI9JoeT/2vh96+9Oqf/ozCHtsgsST5aiHTahSkaV5a6cQvxVXDMaKXWjepftqdTGACqppjG5RYPD2c=
  - secure: X24XwVNo7wVVJCx8NxIpiXs0KcwY9+X1VXajcWPndZk3zcUvDGGNXHOCdWz6qkoRfM5ZdKH9Xdt6U0Mjz1LsxZzH1GXk3TdxWUtNtkI47yEHZoo25ZHPAin5E+dlDMIGOUS332q7ckmogQvk87t8LmmkobPgB1+m+sma9l9c8rI=
  - secure: KSzzDmclC7D1mf3+iW1YYF6NDfI7Tz7QikPjQxik1WYnfKD1xAV6aLKjTO1OOxGgqYns+5LfdwprIk6Fmh8XxEXEjgqlW4yeREA+FTaLD1yiinT95C5g9M53VyLBsnLAYLUqavhGUC8GAMq/NxykFJq6LyXeUnsTR9t1UgS5t2Q=
  - secure: SXK4UctuRExL923ZlcbaBFjUvi5J6SxzClBZEmaeePH0JJc0W+nJ9ttXLI08ESmlmPg9+74nz3FohmPDqjLH9VJbboPjkR8vAaOUsqlj3cIlFe80ow9iXLKHwcRHF9syHNMN+naLoq/tKIN6/9Qnez9Y08pbDGdq9axe8O1xBWo=
  - secure: Pa7upaTZfT88Esd2WsCBEn+/ZpwUiyPiXiSmeIa+eVzPvSiXPSw67mR7scbcCGtRnrQwbVQhJWq+aNUx1xvuHv4ZJNP7b2qg5evdrUogMM0DAS6giP2QyTrB4jaY7hal4elm8b77Lp4AMcFlOmkv4lmXdvZb5Jodgyo3wWF2xx4=
  - secure: SFVWLH7CI6Uu6J1qD+br0LwpH+K8A7txb/eCKmm9irhjaJcYKZkkJkByZJUP9Djb8IkXFA01BbvDC+LOg8OHt3S3mTaCpWTcf9A8fgprVELVp0J5R5cYzvuytwyQ+EsYz/yrDMjDSiNl1X27R4kcYtZxq3DnBkH1mW4voADmnNg=
  - secure: YsiAEsdvD+Svx0sSID/asyWFkhkS6BB+lZcuWbT44LIqQwr+TptHvvu+dpSvRQM89ZP/BcRKWgj0hSGRVbOHsQERoJcnKtAom14zR5zE8UJPPb9/vYNffnAl0B0RL2/J4tgYDBTD83jAoU99TEKCw7alUsXWUj+vesBe0/o8Rc8=
  - secure: l77cCX2Rt9J7F/y8/ey2JWXR4448BZ11oS00v+fLdq8eG8FmNnWKcRS0krFA/ma4gUQ82ZOGdtXTzGWIP40/IMTdEE2YL3Xg4kh+8OzWb2lDiYXE4RuqLEPbEY42xn17YMtZWUGi+618KA3nF8Z6Euo4o8YvlWW/LB9pwNBPdqY=
  - secure: LlNqPL7wjDK4i+TBbi8+t+komYbIDRWinS/atffK+z5Avc6d9+nK8aEilPGDesopJrYVh6aLd5HrfbUYLQM8iJgfGWaHZpzRWzMrFTlqUKJZHoej8AeD2xk/YO1dN21zykQEIRR4GfxvAV7eUy7lyndNqEhApz41gVMPCquf9HU=
  - secure: KLTQdJwYYROIoT7N4+nVpaMBwgcIKgEnFjcqi1/cIRAs4UYnNYsmy8TXwK1473aRtNe0wWah9ioKlDjCNMgq/hO3kUfgArPqk8xAZSVrXg0B7C7zxCYUAT0PxOvZl/PwIRfti536X+Q3FbLyIHyPn3FQQYWXdF6NQp5lUObaw5I=
  - secure: ixnI4hsKGasN6u6kX/mL+oSpo8UOY9KvatdpxencSNnGBtrEw/oT+h13zWStA4J3vCSacbAaH81D8bp+JU/uSf2JHmMTDIMjBzHcuu56kqVe+RIuEDtN48UKAyoil3eUBtLe21gEZoktweu6xzt9G9OooeDl6U7FNkp6sGTRcM8=
  - secure: qjWp8J5TiyQIxalHA8i/Qm8IdkHpH78XOH9SX2xbDJfMDziU0ooIWsdFd1IZ41KNTZXdaeczYHdb2hQRNpAq3Oy9AeWOEerV/3bkbdgMBPn/xARdQPgR3nMZGKeNUV4YL6tVFhgcfOrBWbttHd3M/MgtlLIcRV0u05CmVsaf+J0=
  - secure: Wwinu3i0nXuJhZzTBjDJbBgU69JZta9Zu0j+29el8T9QrVOJHcijoXcp4ky6GfjoKP3jBw/39RzatI3kQczOfpGeBxFMJfSfXSsXheh0oopni74LE06VdgDst0lReVL+GpG4TmdzikIrlI0w5Y11KnwZfCEPjs87td4HRweNa/8=
