---
services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:80"
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mariadb
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./tmp:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db-data:
