<?php echo $this->doctype(); ?>

<html lang="hu">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
	<meta property="fb:admins" content="1819502454" />
	<title><?php if(isset($pagetitle)) echo $pagetitle; ?></title>
	<meta name="description" content="A teljes Szentírás, azaz a Biblia magyarul az interneten: katolikus és protestáns fordításban">
	<meta name="keywords" content="biblia, katolikus, protestáns, szentírás, keresztény, keresztyén, református, hivatalos">

	<meta name="author" content="szentiras.hu">

	<meta http-equiv="cleartype" content="on">

	<meta property="og:image" content="http://szentiras.hu/img/biblia.jpg">
	<?php echo $meta ?>

	
	<!--<link rel="shortcut icon" href="/favicon.ico">-->

	<!-- Responsive and mobile friendly stuff -->
	<meta name="HandheldFriendly" content="True">
	<meta name="MobileOptimized" content="320">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/html5reset.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . "/css/bootstrap.min.css")
                        ->prependStylesheet($this->basePath() . "/css/responsivegridsystem.css")
                        ->prependStylesheet($this->basePath() . "/css/col.css")
                        ->prependStylesheet($this->basePath() . "/css/2cols.css")
                        ->prependStylesheet($this->basePath() . "/css/search.css")                
                        ->prependStylesheet($this->basePath() . "/css/style.css")                
        ?>



        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/modernizr-2.5.3-min.js')
            ->prependFile($this->basePath() . '/js/search.js')
                
        ; ?>

    </head>
    <body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-36302080-1', 'szentiras.hu');
  ga('send', 'pageview');
</script>        

        <div id="skiptomain"><a href="#maincontent">Irány a tartalom</a></div>
        <div id="wrapper">
                <div id="headcontainer">
                    <?php 
                        if(getvar('dolgozunk')=='true') 
                            echo '<div algin="center" style="background-color:red;color:white;text-align:center">Éppen fejlesztünk! Ha furcsa dolgot lát, kérjük frissítse az oldalt, vagy térjen vissza pár perc múlva!</div>'; 

                        foreach($translations as $t) {            
                            if(getvar('frissitunk_'.$t['abbrev'])=='true') 
                                echo '<div algin="center" style="background-color:red;color:white;text-align:center">Éppen frissítjük a '.$t['abbrev'].' szövegeket! Az ebből fakadó hibákért elnézést kérünk!</div>'; 
                        }
                    ?>
                    <header>
                        <h1><a href="<?php if(isset($baseurl)) echo $baseurl; ?>" style="color:white"><?php if(isset($sitetitle)) echo $sitetitle; ?></a></h1>
                            <?php if(isset($subsitetitle)) echo "<h2>".$subsitetitle."</h2>"; ?>
                    </header>
                </div>
                <div id="maincontentcontainer">
                    <div id="maincontent">
                        <div class="section group">	
                            <div class="col span_2_of_2" style="float: right;position: relative;">
                                <div id="share"><?php echo $share; ?></div>
                                <?php if(isset($title)) echo "<h4>".$title."</h4>"; ?>
                                <?php if(isset($hir)) 
                                    echo '<div algin="center" style="background-color:#373A8D;color:white;padding-left:3px;margin-bottom:3px">'.$hir.'</div>'; 
                                ?>
                                <?php
                                    if(isset($hirek) and is_array($hirek)) { 
                                        if(!is_array($hirek[0])) $hirek[0] = $hirek;
                                        foreach($hirek as $hir) {
                                            echo '<div algin="center" class="menu" style="background-color:#9DA7D8;color:white;padding-left:3px;margin-bottom:3px"><div class="menulink clicktoopen">'.$hir[0].'</div><div class="openit" style="display:none;">'.$hir[1].'</div></div>'; 
                                        }
                                    }
                                ?>
                                <?php 
                                    if(isset($content)) echo $content; 
                                    echo "<br>".$abbrevlist;
                                ?>
                            </div>
                            <div class="col span_1_of_2" style="position: relative;">
                                <?php if(isset($menu->items)) $menu->html(); ?>
                            </div>
                        </div>			
                        <div class="section group" style="margin-top:30px">	
                            <div class="col span_2_of_2" style="float: right;position: relative;">
                                <?php if(isset($comments) AND $comments != '') {
                                    echo "<h4>Kommentár</h4>";
                                    echo $comments; 
                                } ?>
                        </div>
                    </div>
                </div>
            </div>
            <div id="footercontainer">
                <footer class="group">
                    <div class="col span_1_of_2">
                        <?php if(isset($copyright)) echo $copyright; ?>
                    </div>
                    <div class="col span_2_of_2">
                        <p>Kérdések, ötletek, problémák: <a href='mailto:eleklaszlosj@gmail.com'>Elek László SJ</a> (<a href="http://jezsuita.hu">JTMR</a>)</p>
                    </div>
                    <br class="breaker" />
                </footer>
            </div>
        </div>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/jquery-1.7.2.min.js"><\/script>')</script>        
        <?php echo $this->inlineScript() ?>        
    </body>
</html>
