#!/bin/bash
echo Updating deployment
DIR=/home/szentiras_hu_git/github/borazslo/szentiras.hu
cd $DIR
echo $PWD
unset GIT_DIR
git checkout mvc
git pull
export MYSQL_SZENTIRAS_USER=
export MYSQL_SZENTIRAS_PASSWORD=
export SZENTIRAS_WEBAPP_ENVIRONMENT=staging
# only install is needed, as dependency versions should be locked
php composer.phar install
php artisan migrate
php artisan up
