#!/bin/bash
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo Received ref $refname meaning branch $branch
    echo Branch $branch push received
    echo Shutting down the app
    cd /home/szentiras_hu_git/github/borazslo/
    if [ ! -d "$branch.szentiras.hu" ]; then
      git clone szentiras.hu.git $branch.szentiras.hu
    fi
    cd $branch.szentiras.hu
    if [ -f composer.lock ]; then
       php artisan down
    fi
done
