#!/bin/bash
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo Received ref $refname as $branch
    echo Shutting down the app
    cd $appEnv.szentiras.hu
    if [ -f composer.lock ]; then
       php artisan down
    fi
    echo Updating deployment
    if [ "$branch" == "master" ]; then
      appEnv=staging
    else
      appEnv=$branch
    fi
    cd /home/szentiras_hu_git/github/borazslo/$appEnv.szentiras.hu
    unset GIT_DIR
    git checkout $branch
    git pull
    echo "<?php return [ 'hash' => '`git rev-parse HEAD`' ];" > config/version.php
    sh install.sh
    php artisan up
done