#!/bin/sh
set -e

php artisan migrate -n
php artisan view:clear
php artisan config:clear
php artisan route:clear
php artisan cache:clear
php artisan twig:clean

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

exec "$@"
