name: Szentiras Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 15432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xml,zip,gd,mbstring,curl,pgsql
 
          ini-values: |
            memory_limit = 512M
          tools: composer

      - name: Install Dependencies
        run: php composer.phar install

      - name: Wait for PostgreSQL to Be Ready
        run: sleep 15

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Create Databases
        env:
          PGPASSWORD: postgres
        run: |
          psql -h 127.0.0.1 -U postgres -c \"CREATE USER homestead WITH PASSWORD 'secret';\""                  
          createdb --owner=homestead bible_testing
          psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE bible_testing;"
          psql -h 127.0.0.1 -U postgres -d bible_testing -c "CREATE EXTENSION IF NOT EXISTS vector;"

      - name: Set Environment Variables
        run: |
          echo "DB_HOST=127.0.0.1" >> .env.testing

      - name: Run Migrations
        run: php artisan migrate --env=testing

      - name: Seed Database
        run: php artisan db:seed --env=testing

      - name: Run Tests
        run: php artisan test