name: Szentiras Smoke Test

on:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Step
        run: echo "This action does nothing but will succeed."